
from __future__ import annotations

import shutil
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.patches import Patch


# =============================
# User settings
# =============================

EXCEL_FILE = Path("analysis_output") / "participant_summary.xlsx"
SHEET_NAME = "participant_summary"

FIGURES_DIR = Path("analysis_output") / "figures"
CLEAR_OLD_FIGURES = True

MEANINGFUL_COLOUR = "#1f77b4"
NOT_MEANINGFUL_COLOUR = "#d62728"

GAMEPLAY_DURATION_COLUMN = "time_gameplay_sec"

SUPPLEMENTARY_TIME_COLUMNS = [
    "time_demographics_to_pre_mcq_sec",
    "time_game_finish_to_post_mcq_sec",
    "time_post_mcq_to_post_questionnaire_sec",
]

SUPPLEMENTARY_TIME_LABELS = {
    "time_demographics_to_pre_mcq_sec": "Pre-game MCQ",
    "time_game_finish_to_post_mcq_sec": "Post-game MCQ",
    "time_post_mcq_to_post_questionnaire_sec": "Post-game AIM/feedback",
}


PRE_POST_PLOTS = [
    {
        "pre_col": "pre_mcq_total_correct",
        "post_col": "post_mcq_total_correct",
        "title": "Pre-post change: MCQ score",
        "y_label": "MCQ score",
        "y_min": 0,
        "y_max": 7,
        "output": "pre_post_mcq_score.png",
    },
    {
        "pre_col": "mri_anxiety_pre",
        "post_col": "mri_anxiety_post",
        "title": "Pre-post change: MRI anxiety",
        "y_label": "MRI anxiety",
        "y_min": 0,
        "y_max": 10,
        "output": "pre_post_mri_anxiety.png",
    },
    {
        "pre_col": "mri_willingness_pre",
        "post_col": "mri_willingness_post",
        "title": "Pre-post change: MRI willingness",
        "y_label": "MRI willingness",
        "y_min": 0,
        "y_max": 10,
        "output": "pre_post_mri_willingness.png",
    },
]

CHANGE_COLUMNS = [
    "mcq_correct_change",
    "mri_anxiety_change",
    "mri_willingness_change",
]

AIM_COLUMNS = [
    "aim_1",
    "aim_2",
    "aim_3",
    "aim_4",
]

# The study data use "completely_agree" and "completely_disagree".
# The normalisation function also accepts equivalent "strongly_*" labels.
AIM_RESPONSE_ORDER = [
    "completely_disagree",
    "disagree",
    "neither_agree_nor_disagree",
    "agree",
    "completely_agree",
    "not_answered",
]

AIM_DISPLAY_LABELS = {
    "completely_disagree": "Completely disagree",
    "disagree": "Disagree",
    "neither_agree_nor_disagree": "Neither agree nor disagree",
    "agree": "Agree",
    "completely_agree": "Completely agree",
    "not_answered": "Not answered",
}

AIM_COLOURS = {
    "completely_disagree": "#d73027",
    "disagree": "#fc8d59",
    "neither_agree_nor_disagree": "#fee08b",
    "agree": "#91bfdb",
    "completely_agree": "#4575b4",
    "not_answered": "#d9d9d9",
}

COLUMN_LABELS = {
    "time_demographics_to_pre_mcq_sec": "Demographics → pre-MCQ",
    "time_gameplay_sec": "Gameplay duration",
    "time_game_finish_to_post_mcq_sec": "Game finished → post-MCQ",
    "time_post_mcq_to_post_questionnaire_sec": (
        "Post-MCQ → post-questionnaire"
    ),
    "mcq_correct_change": "MCQ score change",
    "mri_anxiety_change": "MRI anxiety change",
    "mri_willingness_change": "MRI willingness change",
    "aim_1": "AIM 1",
    "aim_2": "AIM 2",
    "aim_3": "AIM 3",
    "aim_4": "AIM 4",
}


# =============================
# General helpers
# =============================

def pretty_label(column_name: str) -> str:
    """
    Return a readable display label for a dataframe column.
    """
    return COLUMN_LABELS.get(
        column_name,
        column_name.replace("_", " "),
    )


def load_data() -> pd.DataFrame:
    """
    Load the participant summary generated by the Excel-processing script.
    """
    if not EXCEL_FILE.exists():
        raise FileNotFoundError(
            f"Could not find Excel file: {EXCEL_FILE.resolve()}\n"
            "Run make_excel_summary_publication.py first."
        )

    dataframe = pd.read_excel(
        EXCEL_FILE,
        sheet_name=SHEET_NAME,
    )

    if dataframe.empty:
        raise RuntimeError(
            "The Excel worksheet was loaded, but it contains no "
            "participant rows."
        )

    if "meaningful_completion" not in dataframe.columns:
        raise RuntimeError(
            "Could not find required column: meaningful_completion"
        )

    return dataframe


def prepare_output_folders() -> dict[str, Path]:
    """
    Create a clean set of figure-output folders.

    If CLEAR_OLD_FIGURES is True, the previous figures directory is
    deleted first. This prevents discontinued or outdated plots from
    remaining in the output.
    """
    if CLEAR_OLD_FIGURES and FIGURES_DIR.exists():
        shutil.rmtree(FIGURES_DIR)

    folders = {
        "time": FIGURES_DIR / "time_plots",
        "pre_post": FIGURES_DIR / "pre_post_plots",
        "numeric": FIGURES_DIR / "numeric_plots",
        "aim": FIGURES_DIR / "aim_plots",
    }

    for folder in folders.values():
        folder.mkdir(
            parents=True,
            exist_ok=True,
        )

    return folders


def is_meaningful(value) -> bool:
    """
    Interpret values from the meaningful_completion Excel column.
    """
    if isinstance(value, bool):
        return value

    if pd.isna(value):
        return True

    text = str(value).strip().lower()

    if text in {"true", "1", "yes", "y"}:
        return True

    if text in {"false", "0", "no", "n"}:
        return False

    return bool(value)


def safe_numeric_series(
    dataframe: pd.DataFrame,
    column: str,
) -> pd.Series:
    """
    Convert a dataframe column to numeric values.

    Invalid values are converted to missing values.
    """
    return pd.to_numeric(
        dataframe[column],
        errors="coerce",
    )


def calculate_x_limits_from_zero(
    values: pd.Series,
) -> tuple[float, float]:
    """
    Calculate an x-axis range for duration plots.

    The substantive scale begins at zero, with a small visual margin
    on either side to prevent points at zero or at the maximum value
    from being clipped.
    """
    numeric_values = pd.to_numeric(
        values,
        errors="coerce",
    ).dropna()

    if numeric_values.empty:
        return -0.5, 1.0

    observed_maximum = float(numeric_values.max())

    if observed_maximum <= 0:
        return -0.5, 1.0

    margin = max(
        observed_maximum * 0.03,
        1.0,
    )

    return -margin, observed_maximum + margin


def scatter_points_on_line(
    axis,
    dataframe: pd.DataFrame,
    x_values: pd.Series,
    y_value: float,
    point_size: int = 45,
) -> None:
    """
    Plot participant values directly on a single horizontal line.

    Participants satisfying meaningful-completion criteria are shown
    in blue. Those not satisfying the criteria are shown in red.
    """
    values = pd.to_numeric(
        x_values,
        errors="coerce",
    )

    valid = values.notna()

    if valid.sum() == 0:
        return

    meaningful_status = dataframe[
        "meaningful_completion"
    ].apply(is_meaningful)

    meaningful_mask = valid & meaningful_status
    non_meaningful_mask = valid & ~meaningful_status

    axis.scatter(
        values[meaningful_mask],
        np.full(
            meaningful_mask.sum(),
            y_value,
        ),
        color=MEANINGFUL_COLOUR,
        s=point_size,
        alpha=0.85,
        edgecolors="black",
        linewidths=0.3,
        zorder=3,
    )

    # Plot non-meaningful completions afterwards so red points remain
    # visible where values overlap.
    axis.scatter(
        values[non_meaningful_mask],
        np.full(
            non_meaningful_mask.sum(),
            y_value,
        ),
        color=NOT_MEANINGFUL_COLOUR,
        s=point_size,
        alpha=0.95,
        edgecolors="black",
        linewidths=0.3,
        zorder=4,
    )


# =============================
# Time plots
# =============================

def plot_single_time_line(
    dataframe: pd.DataFrame,
    column: str,
    title: str,
    output_path: Path,
) -> None:
    """
    Plot one duration variable as participant points on a horizontal line.
    """
    if column not in dataframe.columns:
        print(f"{column} not found. Skipping.")
        return

    values = safe_numeric_series(
        dataframe,
        column,
    )

    if values.notna().sum() == 0:
        print(
            f"No valid values for {column}. Skipping."
        )
        return

    x_minimum, x_maximum = calculate_x_limits_from_zero(
        values
    )

    figure, axis = plt.subplots(
        figsize=(10, 2.4)
    )

    axis.hlines(
        y=0,
        xmin=0,
        xmax=x_maximum,
        color="black",
        linewidth=0.9,
        alpha=0.7,
    )

    scatter_points_on_line(
        axis=axis,
        dataframe=dataframe,
        x_values=values,
        y_value=0,
        point_size=55,
    )

    axis.set_xlim(
        x_minimum,
        x_maximum,
    )

    axis.set_ylim(
        -0.45,
        0.45,
    )

    axis.set_yticks([])

    axis.set_xlabel("Time, seconds")
    axis.set_title(title)

    axis.grid(
        axis="x",
        alpha=0.25,
    )

    axis.spines["top"].set_visible(False)
    axis.spines["right"].set_visible(False)
    axis.spines["left"].set_visible(False)

    figure.tight_layout()

    figure.savefig(
        output_path,
        dpi=300,
    )

    plt.close(figure)


def plot_time_panel(
    dataframe: pd.DataFrame,
    columns: list[str],
    title: str,
    output_path: Path,
    custom_labels: dict[str, str] | None = None,
) -> None:
    """
    Plot several duration variables together using a shared x-axis.
    """
    existing_columns = [
        column
        for column in columns
        if column in dataframe.columns
    ]

    if not existing_columns:
        print(
            f"No columns found for {title}. Skipping."
        )
        return

    all_values = pd.concat(
        [
            safe_numeric_series(
                dataframe,
                column,
            )
            for column in existing_columns
        ],
        axis=0,
    )

    if all_values.notna().sum() == 0:
        print(
            f"No valid values for {title}. Skipping."
        )
        return

    x_minimum, x_maximum = calculate_x_limits_from_zero(
        all_values
    )

    number_of_rows = len(existing_columns)
    figure_height = max(
        3.0,
        number_of_rows * 0.9,
    )

    figure, axis = plt.subplots(
        figsize=(10, figure_height)
    )

    y_positions = list(
        range(number_of_rows)
    )[::-1]

    for column, y_position in zip(
        existing_columns,
        y_positions,
    ):
        axis.hlines(
            y=y_position,
            xmin=0,
            xmax=x_maximum,
            color="black",
            linewidth=0.8,
            alpha=0.55,
        )

        scatter_points_on_line(
            axis=axis,
            dataframe=dataframe,
            x_values=dataframe[column],
            y_value=y_position,
            point_size=50,
        )

    axis.set_xlim(
        x_minimum,
        x_maximum,
    )

    axis.set_ylim(
        -0.7,
        number_of_rows - 0.3,
    )

    axis.set_yticks(y_positions)

    if custom_labels is None:
        labels = [
            pretty_label(column)
            for column in existing_columns
        ]
    else:
        labels = [
            custom_labels.get(
                column,
                pretty_label(column),
            )
            for column in existing_columns
        ]

    axis.set_yticklabels(labels)

    axis.set_xlabel("Time, seconds")
    axis.set_title(title)

    axis.grid(
        axis="x",
        alpha=0.25,
    )

    axis.spines["top"].set_visible(False)
    axis.spines["right"].set_visible(False)

    figure.tight_layout()

    figure.savefig(
        output_path,
        dpi=300,
    )

    plt.close(figure)


# =============================
# Pre-post connected plots
# =============================

def plot_pre_post_connected(
    dataframe: pd.DataFrame,
    pre_column: str,
    post_column: str,
    title: str,
    y_label: str,
    y_minimum: int,
    y_maximum: int,
    output_path: Path,
) -> None:
    """
    Plot paired pre-post participant values.

    Individual participant trajectories are shown as connecting lines.
    One aggregated marker is displayed at each observed pre/post value,
    with the number of participants at that value printed inside.
    """
    if (
        pre_column not in dataframe.columns
        or post_column not in dataframe.columns
    ):
        print(
            f"Missing {pre_column} or {post_column}. "
            f"Skipping {title}."
        )
        return

    pre_values = safe_numeric_series(
        dataframe,
        pre_column,
    )

    post_values = safe_numeric_series(
        dataframe,
        post_column,
    )

    valid = (
        pre_values.notna()
        & post_values.notna()
    )

    # Apply the same MCQ-specific meaningful-completion gate used for the
    # MCQ change-score bar chart. Participants must have attempted at least
    # 5 of 7 MCQ items at BOTH pre and post to appear in the MCQ trajectory
    # plot. Participants who failed meaningful completion only for another
    # reason (for example, NPC interactions < 8) remain eligible.
    #
    # Anxiety and willingness trajectory plots retain their existing
    # behaviour and require only valid paired pre/post values.
    if (
        pre_column == "pre_mcq_total_correct"
        and post_column == "post_mcq_total_correct"
    ):
        valid = (
            valid
            & get_mcq_meaningful_completion_mask(
                dataframe
            )
        )

    if valid.sum() == 0:
        print(
            f"No valid data for {title}. Skipping."
        )
        return

    figure, axis = plt.subplots(
        figsize=(5.2, 5.2)
    )

    # Draw participant-level connecting lines first.
    for participant_index in dataframe.index[valid]:
        colour = (
            MEANINGFUL_COLOUR
            if is_meaningful(
                dataframe.loc[
                    participant_index,
                    "meaningful_completion",
                ]
            )
            else NOT_MEANINGFUL_COLOUR
        )

        axis.plot(
            [0, 1],
            [
                pre_values.loc[participant_index],
                post_values.loc[participant_index],
            ],
            color=colour,
            alpha=0.28,
            linewidth=1.2,
            zorder=1,
        )

    # Draw aggregated markers for each observed score at pre and post.
    for x_position, values in [
        (0, pre_values),
        (1, post_values),
    ]:
        valid_values = values[valid]

        rounded_values = (
            valid_values
            .round()
            .astype(int)
        )

        counts_by_score = (
            rounded_values
            .value_counts()
            .sort_index()
        )

        for score, count in counts_by_score.items():
            participant_indices_at_score = rounded_values[
                rounded_values == score
            ].index

            number_meaningful = sum(
                is_meaningful(
                    dataframe.loc[
                        participant_index,
                        "meaningful_completion",
                    ]
                )
                for participant_index
                in participant_indices_at_score
            )

            number_non_meaningful = (
                count - number_meaningful
            )

            if number_non_meaningful == 0:
                marker_colour = MEANINGFUL_COLOUR

            elif number_meaningful == 0:
                marker_colour = NOT_MEANINGFUL_COLOUR

            else:
                marker_colour = "#7b3294"

            marker_size = 160 + (count - 1) * 35

            axis.scatter(
                x_position,
                score,
                color=marker_colour,
                s=marker_size,
                alpha=0.95,
                edgecolors="black",
                linewidths=0.7,
                zorder=3,
            )

            axis.text(
                x_position,
                score,
                str(count),
                ha="center",
                va="center",
                fontsize=8,
                fontweight="bold",
                color="white",
                zorder=4,
            )

    axis.set_xticks([0, 1])
    axis.set_xticklabels(["Pre", "Post"])

    axis.set_xlim(
        -0.25,
        1.25,
    )

    axis.set_ylim(
        y_minimum - 0.5,
        y_maximum + 0.5,
    )

    axis.set_yticks(
        np.arange(
            y_minimum,
            y_maximum + 1,
            1,
        )
    )

    axis.set_ylabel(y_label)
    axis.set_title(title)

    axis.grid(
        axis="y",
        alpha=0.25,
    )

    axis.spines["top"].set_visible(False)
    axis.spines["right"].set_visible(False)

    figure.tight_layout()

    figure.savefig(
        output_path,
        dpi=300,
    )

    plt.close(figure)


# =============================
# Numeric change bar charts
# =============================

def get_integer_change_series_preserve_index(
    values: pd.Series,
) -> pd.Series:
    """
    Convert change scores to nullable integers while preserving the
    original dataframe index.
    """
    numeric_values = pd.to_numeric(
        values,
        errors="coerce",
    )

    rounded_values = numeric_values.round()

    return rounded_values.astype("Int64")


def get_change_axis_range(
    integer_values: pd.Series,
) -> tuple[int, int]:
    """
    Determine the displayed change-score range from the observed values,
    while always including zero.
    """
    valid_values = integer_values.dropna()

    if valid_values.empty:
        return -1, 1

    observed_minimum = int(
        valid_values.min()
    )

    observed_maximum = int(
        valid_values.max()
    )

    x_minimum = min(
        observed_minimum,
        0,
    )

    x_maximum = max(
        observed_maximum,
        0,
    )

    if x_minimum == x_maximum:
        x_minimum -= 1
        x_maximum += 1

    return x_minimum, x_maximum


def get_mcq_meaningful_completion_mask(
    dataframe: pd.DataFrame,
) -> pd.Series:
    """
    Return a Boolean mask identifying participants who met the MCQ-specific
    meaningful-completion requirement: at least 5 of 7 MCQ items attempted
    at both pre- and post-game timepoints.

    The explicit pre_mcq_attempted and post_mcq_attempted columns are used
    when available. If either column is unavailable, the function falls back
    to the standardised meaningful_completion_failure_reason text generated
    by the step-1 summary script.
    """
    if (
        "pre_mcq_attempted" in dataframe.columns
        and "post_mcq_attempted" in dataframe.columns
    ):
        pre_attempted = pd.to_numeric(
            dataframe["pre_mcq_attempted"],
            errors="coerce",
        )

        post_attempted = pd.to_numeric(
            dataframe["post_mcq_attempted"],
            errors="coerce",
        )

        return (
            pre_attempted.ge(5)
            & post_attempted.ge(5)
        )

    if "meaningful_completion_failure_reason" in dataframe.columns:
        failure_reason = (
            dataframe["meaningful_completion_failure_reason"]
            .fillna("")
            .astype(str)
            .str.lower()
        )

        failed_mcq_completion = (
            failure_reason.str.contains(
                "pre mcq attempted <",
                regex=False,
            )
            | failure_reason.str.contains(
                "post mcq attempted <",
                regex=False,
            )
        )

        return ~failed_mcq_completion

    # Defensive fallback: if the MCQ-specific completion information is
    # unavailable, retain all rows and let missing change scores be excluded
    # in the usual way.
    print(
        "Warning: MCQ completion columns were not found. "
        "MCQ change plot will use all participants with valid change scores."
    )

    return pd.Series(
        True,
        index=dataframe.index,
    )


def plot_change_bar_chart(
    dataframe: pd.DataFrame,
    column: str,
    output_path: Path,
) -> None:
    """
    Plot the frequency distribution of an integer change score.

    Bars are stacked by overall meaningful-completion status.

    For the MCQ change-score plot only, participants are additionally
    required to have attempted at least 5 of 7 MCQ items at both pre- and
    post-game timepoints. Participants who failed meaningful completion
    solely for another reason (for example, NPC interactions < 8) remain
    eligible for the MCQ plot provided that their MCQ completion was
    sufficient and a valid change score is available.

    Anxiety and willingness plots retain the existing behaviour and include
    all participants with a valid change score for the respective outcome.
    """
    if column not in dataframe.columns:
        print(
            f"{column} not found. Skipping."
        )
        return

    integer_values = (
        get_integer_change_series_preserve_index(
            dataframe[column]
        )
    )

    if column == "mcq_correct_change":
        mcq_completion_mask = (
            get_mcq_meaningful_completion_mask(
                dataframe
            )
        )

        integer_values = integer_values.where(
            mcq_completion_mask
        )

    if integer_values.dropna().empty:
        print(
            f"No valid data for {column}. Skipping."
        )
        return

    x_minimum, x_maximum = get_change_axis_range(
        integer_values
    )

    x_values = list(
        range(
            x_minimum,
            x_maximum + 1,
        )
    )

    meaningful_mask = dataframe[
        "meaningful_completion"
    ].apply(is_meaningful)

    non_meaningful_mask = ~meaningful_mask

    meaningful_counts: list[int] = []
    non_meaningful_counts: list[int] = []

    for x_value in x_values:
        value_mask = (
            integer_values == x_value
        )

        meaningful_counts.append(
            int(
                (
                    value_mask
                    & meaningful_mask
                ).sum()
            )
        )

        non_meaningful_counts.append(
            int(
                (
                    value_mask
                    & non_meaningful_mask
                ).sum()
            )
        )

    stacked_totals = (
        np.array(meaningful_counts)
        + np.array(non_meaningful_counts)
    )

    maximum_count = (
        int(stacked_totals.max())
        if len(stacked_totals) > 0
        else 1
    )

    if maximum_count < 1:
        maximum_count = 1

    figure, axis = plt.subplots(
        figsize=(8, 4.2)
    )

    axis.bar(
        x_values,
        meaningful_counts,
        width=0.8,
        color=MEANINGFUL_COLOUR,
        edgecolor="black",
        linewidth=0.4,
        label="Meaningful completion",
    )

    axis.bar(
        x_values,
        non_meaningful_counts,
        width=0.8,
        bottom=meaningful_counts,
        color=NOT_MEANINGFUL_COLOUR,
        edgecolor="black",
        linewidth=0.4,
        label="Did not meet meaningful completion",
    )

    # Display the observed participant count and percentage in the centre
    # of each non-zero stacked bar. Percentages use the number of participants
    # actually eligible for and represented in this change-score plot as the
    # denominator. For MCQ this therefore excludes participants who attempted
    # fewer than 5 items at either pre or post, in addition to missing change
    # scores. Anxiety and willingness retain their existing valid-pair
    # denominators.
    valid_participant_count = int(integer_values.notna().sum())

    for x_value, total_count in zip(
        x_values,
        stacked_totals,
    ):
        if total_count <= 0:
            continue

        percentage = (
            100.0 * float(total_count) / valid_participant_count
            if valid_participant_count > 0
            else 0.0
        )

        axis.text(
            x_value,
            float(total_count) / 2.0,
            f"{int(total_count)} ({percentage:.1f}%)",
            ha="center",
            va="center",
            fontsize=7,
            fontweight="bold",
            color="white",
            clip_on=True,
            zorder=5,
        )

    axis.set_xlim(
        x_minimum - 0.7,
        x_maximum + 0.7,
    )

    axis.set_xticks(x_values)

    axis.set_ylim(
        0,
        maximum_count + 0.5,
    )

    axis.set_yticks(
        range(
            0,
            maximum_count + 1,
            1,
        )
    )

    axis.set_ylabel("Number of participants")
    axis.set_xlabel(pretty_label(column))
    axis.set_title(pretty_label(column))

    axis.grid(
        axis="y",
        alpha=0.25,
    )

    axis.spines["top"].set_visible(False)
    axis.spines["right"].set_visible(False)

    axis.legend(
        loc="upper center",
        bbox_to_anchor=(0.5, -0.18),
        ncol=2,
        frameon=False,
        fontsize=8,
    )

    figure.tight_layout()

    figure.savefig(
        output_path,
        dpi=300,
        bbox_inches="tight",
    )

    plt.close(figure)


# =============================
# AIM plot
# =============================

def normalise_aim_response(value) -> str:
    """
    Convert AIM responses to the standard categories used for plotting.

    Missing or blank responses are represented as not_answered.
    """
    if pd.isna(value):
        return "not_answered"

    text = str(value).strip()

    if text == "":
        return "not_answered"

    text = (
        text
        .lower()
        .replace("-", "_")
        .replace(" ", "_")
    )

    replacements = {
        "completely_disagree": "completely_disagree",
        "strongly_disagree": "completely_disagree",

        "disagree": "disagree",

        "neither": "neither_agree_nor_disagree",
        "neutral": "neither_agree_nor_disagree",
        "neither_agree_nor_disagree":
            "neither_agree_nor_disagree",
        "neither_disagree_nor_agree":
            "neither_agree_nor_disagree",

        "agree": "agree",

        "completely_agree": "completely_agree",
        "strongly_agree": "completely_agree",

        "na": "not_answered",
        "n/a": "not_answered",
        "none": "not_answered",
        "nan": "not_answered",
        "not_answered": "not_answered",
        "missing": "not_answered",
    }

    return replacements.get(
        text,
        text,
    )


def plot_all_aim_items(
    dataframe: pd.DataFrame,
    output_path: Path,
) -> None:
    """
    Plot all four AIM-item response distributions as horizontal
    proportional stacked bars.

    Missing responses are included as a separate category so every
    bar represents the full participant sample.
    """
    existing_aim_columns = [
        column
        for column in AIM_COLUMNS
        if column in dataframe.columns
    ]

    if not existing_aim_columns:
        print(
            "No AIM columns found. Skipping AIM plot."
        )
        return

    total_participants = len(dataframe)

    if total_participants == 0:
        print(
            "No participants found. Skipping AIM plot."
        )
        return

    number_of_items = len(
        existing_aim_columns
    )

    figure_height = max(
        4.6,
        number_of_items * 1.0,
    )

    figure, axis = plt.subplots(
        figsize=(10, figure_height)
    )

    y_positions = list(
        range(number_of_items)
    )[::-1]

    for aim_column, y_position in zip(
        existing_aim_columns,
        y_positions,
    ):
        responses = dataframe[
            aim_column
        ].apply(normalise_aim_response)

        counts = responses.value_counts()

        left_position = 0.0

        for category in AIM_RESPONSE_ORDER:
            number = int(
                counts.get(
                    category,
                    0,
                )
            )

            proportion = (
                number / total_participants
            )

            if number == 0:
                continue

            colour = AIM_COLOURS.get(
                category,
                "#cccccc",
            )

            axis.barh(
                y=y_position,
                width=proportion,
                left=left_position,
                height=0.72,
                color=colour,
                edgecolor="white",
                linewidth=1.0,
            )

            # Use two lines so the label fits more comfortably inside
            # narrow response-category segments.
            label = (
                f"{proportion:.0%}\n"
                f"(n={number})"
            )

            # Keep every label centred within its own segment.
            # Use progressively smaller text for narrower segments.
            if proportion >= 0.12:
                font_size = 8

            elif proportion >= 0.07:
                font_size = 7

            else:
                font_size = 6

            axis.text(
                left_position + proportion / 2,
                y_position,
                label,
                ha="center",
                va="center",
                fontsize=font_size,
                color="black",
                linespacing=0.9,
                clip_on=True,
            )

            left_position += proportion

        known_categories = set(
            AIM_RESPONSE_ORDER
        )

        unexpected_categories = sorted(
            set(counts.index)
            - known_categories
        )

        if unexpected_categories:
            print(
                "Warning: unexpected AIM categories in "
                f"{aim_column}: {unexpected_categories}"
            )

    axis.set_xlim(0, 1)

    axis.set_ylim(
        -0.7,
        number_of_items - 0.3,
    )

    axis.set_yticks(y_positions)

    axis.set_yticklabels(
        [
            pretty_label(column)
            for column in existing_aim_columns
        ]
    )

    axis.set_title(
        "AIM item response distributions"
    )

    axis.set_xticks([])
    axis.set_xlabel("")
    axis.grid(False)

    axis.spines["top"].set_visible(False)
    axis.spines["right"].set_visible(False)
    axis.spines["bottom"].set_visible(False)

    legend_handles = [
        Patch(
            facecolor=AIM_COLOURS[category],
            label=AIM_DISPLAY_LABELS[category],
        )
        for category in AIM_RESPONSE_ORDER
    ]

    axis.legend(
        handles=legend_handles,
        loc="upper center",
        bbox_to_anchor=(0.5, -0.12),
        ncol=3,
        frameon=False,
        fontsize=8,
    )

    figure.tight_layout()

    figure.savefig(
        output_path,
        dpi=300,
        bbox_inches="tight",
    )

    plt.close(figure)


# =============================
# Main
# =============================

def main() -> None:
    dataframe = load_data()
    folders = prepare_output_folders()

    # Main gameplay-duration plot
    plot_single_time_line(
        dataframe=dataframe,
        column=GAMEPLAY_DURATION_COLUMN,
        title="Gameplay duration",
        output_path=(
            folders["time"]
            / "gameplay_duration.png"
        ),
    )

    # Supplementary questionnaire-completion-time plot
    plot_time_panel(
        dataframe=dataframe,
        columns=SUPPLEMENTARY_TIME_COLUMNS,
        title="Questionnaire and feedback completion times",
        output_path=(
            folders["time"]
            / "supplementary_questionnaire_times.png"
        ),
        custom_labels=SUPPLEMENTARY_TIME_LABELS,
    )


    # Paired pre-post plots
    for plot_specification in PRE_POST_PLOTS:
        plot_pre_post_connected(
            dataframe=dataframe,
            pre_column=plot_specification["pre_col"],
            post_column=plot_specification["post_col"],
            title=plot_specification["title"],
            y_label=plot_specification["y_label"],
            y_minimum=plot_specification["y_min"],
            y_maximum=plot_specification["y_max"],
            output_path=(
                folders["pre_post"]
                / plot_specification["output"]
            ),
        )

    # Change-score bar charts
    for change_column in CHANGE_COLUMNS:
        plot_change_bar_chart(
            dataframe=dataframe,
            column=change_column,
            output_path=(
                folders["numeric"]
                / f"{change_column}.png"
            ),
        )

    # Combined AIM response-distribution plot
    plot_all_aim_items(
        dataframe=dataframe,
        output_path=(
            folders["aim"]
            / "aim_all_items_distribution.png"
        ),
    )

    print("Plot generation complete.")
    print(
        f"Input Excel file: {EXCEL_FILE.resolve()}"
    )
    print(
        f"Figures folder: {FIGURES_DIR.resolve()}"
    )

    print("\nCreated plots:")
    print(
        f"- {folders['time'] / 'gameplay_duration.png'}"
    )
    print(
        f"- {folders['time'] / 'supplementary_questionnaire_times.png'}"
    )

    for plot_specification in PRE_POST_PLOTS:
        print(
            f"- {folders['pre_post'] / plot_specification['output']}"
        )

    for change_column in CHANGE_COLUMNS:
        print(
            f"- {folders['numeric'] / f'{change_column}.png'}"
        )

    print(
        f"- {folders['aim'] / 'aim_all_items_distribution.png'}"
    )


if __name__ == "__main__":
    main()
